### PR TITLE
Always handle web socket open when connecting

### LINKED ISSUE #1521: State machine: Unhandled event 'websocket open' in state 'connecting'.
There was some connectivity issues between us-east-1 and slack the other day, and my bot crashed. Looks like the state machine wasn't expecting a 'websocket open' in state 'connecting'

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [x] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

slack/bolt: 3.11.3

#### Node.js runtime version

v16.16.0

#### OS info

#31~20.04.1-Ubuntu SMP Fri Jan 14 14:37:50 UTC 2022

#### Steps to reproduce:

bolt is configured as:

```
  const app = new bolt.App({
    token: config.slack.oauth_token,
    signingSecret: config.slack.signing_secret,
    socketMode: true,
    appToken: config.slack.app_token,
    port: 3000
  });

  await app.start();
```

### Expected result:

Reconnect continues to try until it works

### Actual result:

```
[INFO]  socket-mode:SocketModeClient:0 A pong wasn't received from the server before the timeout of 5000ms!
[INFO]  socket-mode:SocketModeClient:0 Reconnecting to Slack ...
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
[INFO]  socket-mode:SocketModeClient:0 Reconnecting to Slack ...
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
[INFO]  socket-mode:SocketModeClient:0 Now connected to Slack
[INFO]  socket-mode:SocketModeClient:0 A pong wasn't received from the server before the timeout of 5000ms!
[INFO]  socket-mode:SocketModeClient:0 Reconnecting to Slack ...
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
[INFO]  socket-mode:SocketModeClient:0 Reconnecting to Slack ...
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...

/home/slackbot/api/node_modules/finity/lib/core/StateMachine.js:76
      throw new Error('Unhandled event \'' + event + '\' in state \'' + this.currentState + '\'.');
      ^

Error: Unhandled event 'websocket open' in state 'connecting'.
    at StateMachine.handleUnhandledEvent (/home/slackbot/api/node_modules/finity/lib/core/StateMachine.js:76:13)
    at /home/slackbot/api/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (/home/slackbot/api/node_modules/finity/lib/core/TaskScheduler.js:29:7)
    at TaskScheduler.enqueue (/home/slackbot/api/node_modules/finity/lib/core/TaskScheduler.js:19:12)
    at HierarchicalStateMachine.handle (/home/slackbot/api/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
    at WebSocket.<anonymous> (/home/slackbot/api/node_modules/@slack/socket-mode/dist/SocketModeClient.js:415:31)
    at WebSocket.onOpen (/home/slackbot/api/node_modules/ws/lib/event-target.js:144:16)
    at WebSocket.emit (node:events:527:28)
    at WebSocket.setSocket (/home/slackbot/api/node_modules/ws/lib/websocket.js:225:10)
    at ClientRequest.<anonymous> (/home/slackbot/api/node_modules/ws/lib/websocket.js:873:15)
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

### PR DESCRIPTION
**Pull request by WilliamBergamin**
###  Summary

This should resolve #1521 
An edge case seem to be present when the `finite state machine (fns)` is not in the authenticated state and the listeners are initialized. This can happen when the application was connected (initialized), lost connection and is reconnecting.

If for some reason the `web socket open` event is triggered before authentication is successful the `fns` falls-back to handling this event at the `connecting` state level instead of the `submachine`. This causes an `fns` error which terminates the running process.

This pr changes the behavior of the `fns` to ignore `web socket open` events when it is in the `connecting` state and the submachine is not `authenticated`, this should prevent the process from terminating.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

**Comment by WilliamBergamin** [comment]
I've tested these changes locally by allowing certain variables to be public but not sure how we could add unit tests without refactoring part of the package

**Review by seratch — APPROVED** [review]
Thanks for fixing. This should be fine. As you mentioned, writing tests for this module is still hard. It's okay to skip adding tests this time.

File: packages/socket-mode/src/SocketModeClient.ts [hunk 1]
```diff
@@ -275,6 +275,8 @@ export class SocketModeClient extends EventEmitter {
         .transitionTo(State.Disconnecting)
       .on(Event.Failure)
         .transitionTo(State.Disconnected)
+      .on(Event.WebSocketOpen)
+        .ignore()
```
Comment (filmaj) [inline packages/socket-mode/src/SocketModeClient.ts:279]: My only comment is to add a comment here explaining why we ignore it, as you did in the PR description. Future-us will be grateful for the hint!

**Review by filmaj — APPROVED** [review]
LGTM! Left a tiny comment to comment the change to help us in the future 😄
