### PR TITLE
web-api(fix): include file or contents types in file_uploads arguments

### LINKED ISSUE #1743: Typescript type error for `web.files.uploadV2()` arguments when using `file_uploads`
#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [x] `@slack/types`
- [ ] I don't know

#### The Slack SDK version
"slack/web-api": "^7.0.1",

#### Node.js runtime version
v18.16.0

#### OS info
ProductName:            macOS
ProductVersion:         14.1.2
BuildVersion:           23B92
Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64

#### Steps to reproduce:
Here's a code example including some comments regarding the problem I'm facing.
``` typescript
import { WebAPICallResult, WebClient } from '@slack/web-api';

if (!process.env.SLACK_APP_INTEGRATION_TOKEN) {
  throw new Error('SLACK_APP_INTEGRATION_TOKEN environment variable is required');
}

const slackToken = process.env.SLACK_APP_INTEGRATION_TOKEN;

/**
 * Post a message with attached images to a Slack channel
 */
export async function notify(channelId: string, text: string, images: string[] | undefined) {
  try {
    const web = new WebClient(slackToken);

    let result: WebAPICallResult;

    if (images && images.length > 0) {
      // This works and is the recommended way to upload multiple files
      // https://slack.dev/node-slack-sdk/web-api#new-way---upload-multiple-files
      // But I get a type error so I disable type checking
      // @ts-ignore
      result = await web.files.uploadV2({
        initial_comment: text,
        channel_id: channelId,
        file_uploads: images.map(image => {
          return {
            file: image,
            filename: image.split('/').pop() || 'image',
          };
        }),
      });
    } else {
      result = await web.chat.postMessage({
        channel: channelId,
        text,
      });
    }

    if (result.ok) {
      console.info('Message posted successfully:', result);
      return;
    }

    console.error('Error posting message to Slack:', result);
  } catch (error) {
    console.error('Error:', error.message);
  }
}

const [channel, message, ...images] = process.argv.slice(2);

if (!channel || !message) {
  console.error('Error: Missing required arguments');
  console.info('Usage: e2e-notify-slack.ts <channel_id> <message> <image1> <image2> ...');
  console.info('Example: e2e-notify-slack.ts XXXXXXXXX "Hello, world!" ./image1.png ./image2.png');
  process.exit(1);
}
notify(channel, message, images);
```

### Expected result:

No typescript type errors

### Actual result:
```
Argument of type '{ initial_comment: string; channel_id: string; file_uploads: { file: string; filename: string; }[]; }' is not assignable to parameter of type 'FilesUploadV2Arguments'.
  Type '{ initial_comment: string; channel_id: string; file_uploads: { file: string; filename: string; }[]; }' is not assignable to type 'FileUploadBinaryContents & FileThreadDestinationArgumentChannels & FileType & { filename?: string | undefined; initial_comment?: string | undefined; title?: string | undefined; } & { ...; } & TokenOverridable & { ...; }'.
    Property 'file' is missing in type '{ initial_comment: string; channel_id: string; file_uploads: { file: string; filename: string; }[]; }' but required in type 'FileUploadBinaryContents'.ts(2345)
files.d.ts(109, 5): 'file' is declared here.
```

### PR DESCRIPTION
**Pull request by zimeg**
###  Summary

This PR ensures both the `file` and `content` arguments are included in the type for `file_uploads`. Fixes #1743.

### Reviewers

The following snippets can be used to ensure these types are available! Using TypeScript or JSDoc is recommended to experience the full typing experience.

#### Single file uploads

Everything should remain working just as expected:

```ts
(async () => {
    const web = new WebClient(token);
    const result = await web.files.uploadV2({
        channel_id: "C0123456789",
        filename: "GREETINGS.txt",
        content: "hello world",
    });
    console.log(result);
})();
```

#### Multiple file uploads

Multiple file uploads can be done without needing to specify a top-level `file` or `content`. These attributes are still allowed and will be uploaded if provided, but aren't required anymore!

But the main fix of this PR is exposing the types for the `file` and `content` within `file_uploads`:

```ts
(async () => {
    const web = new WebClient(token);
    const result = await web.files.uploadV2({
        channel_id: "C0123456789",
        file_uploads: [
            {
                filename: "README.md",
                file: "./README.md",
            },
            {
                filename: "GREETINGS.txt",
                content: "hello world",
            },
        ]
    });
    console.log(result);
})();
```

### Requirements

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

File: packages/web-api/src/file-upload.ts [hunk 1]
```diff
@@ -47,10 +45,16 @@ export async function getFileUploadJob(
...
+  if ('file' in options) {
+    return {
+      file: options.file,
+      ...fileUploadJob,
+    };
+  }
+  throw errorWithCode(
+    new Error('Either a file or content field is required for valid file upload. You must supply one'),
+    ErrorCode.FileUploadInvalidArgumentsError,
+  );
```
Comment (zimeg) [inline packages/web-api/src/file-upload.ts:57]: Changes to check for the existence of `file` or whatever key is being done for stronger type safety. The error case would be thrown by the API and is moved ahead a bit here. I think this is also checked earlier in the call too, but isn't picked up by the types.

File: packages/web-api/src/types/helpers.ts [hunk 2]
```diff
@@ -0,0 +1,2 @@
+/** Omit all keys K from possible union types T */
+export type ExcludeFromUnion<T, K extends string> = T extends T ? Omit<T, K> : never;
```
Comment (zimeg) [inline packages/web-api/src/types/helpers.ts:2]: `Omit` seems to act strange with union types so instead this helper type is added! The `T extends T` is used to force the type checker to apply the `Omit` to each member of the union.

File: packages/web-api/src/types/request/files.ts [hunk 3]
```diff
@@ -147,10 +148,15 @@ export type FileUploadV2 = FileUpload & {
...
+}
+
 // https://slack.dev/node-slack-sdk/web-api#upload-a-file
-export type FilesUploadV2Arguments = FileUploadV2 & TokenOverridable & {
-  file_uploads?: Omit<FileUploadV2, 'channel_id' | 'channels' | 'initial_comment' | 'thread_ts'>[];
-};
+export type FilesUploadV2Arguments = TokenOverridable & (
+  | FileUploadV2
+  | (Omit<FileUploadV2, 'file' | 'content'> & FilesUploadV2ArgumentsMultipleFiles)
+);
```
Comment (zimeg) [inline packages/web-api/src/types/request/files.ts:159]: This `Omit` seems alright sense the `file` and `content` remain optional in the second case! There's magic deep within the type checker.

**Review by zimeg — COMMENTED** [review]
📝 Some notes for the reviewers!

**Review by seratch — APPROVED** [review]
Cool! Thanks for resolving this!
