### PR TITLE
fix: improve type for upload file v2

### LINKED ISSUE #1846: Using Typescript, filesUploadV2 requires deprecated 'channels' argument when 'thread_ts' is given
#### Packages:

Select all that apply:

- [X] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] `@slack/types`
- [ ] I don't know

#### The Slack SDK version
`"slack/web-api": "^7.3.1",`

#### Node.js runtime version
v21.6.2

### Typescript version
`"typescript": "5.4.5",`

#### Steps to reproduce:

With the following code:

```typescript
    const token = '...';
    const channelId = '...';

    const slack = new WebClient(token);

    const response = await slack.chat.postMessage({
      text: `hello`,
      channel: channelId,
    });

    await slack.filesUploadV2({
      channel_id: channelId,
      thread_ts: response.ts,
      content: 'test',
      filename: 'test.txt',
      title: 'test',
    });
```

I get the following Typescript compile error:

`Property 'channels' is missing in type '{ channel_id: string; thread_ts: string; content: string; filename: string; title: string; }' but required in type 'FileThreadDestinationArgumentChannels'.`

However, if I include the `channels` field, I get a warning at runtime:

`[WARN]  web-api:WebClient:0 Although the 'channels' parameter is still supported for smoother migration from legacy files.upload, we recommend using the new channel_id parameter with a single str value instead (e.g. 'C12345').`

If the `thread_ts` argument is not included, then `channels` is not required.

### PR DESCRIPTION
**Pull request by WilliamBergamin**
###  Summary

This PR aims to fix #1846 by adding additional typing and related tests

### Testing
1. Pull this branch
2. `cd packages/web-api`
3. `npm build`
4. In a project with the following `app.ts`
```ts
import { WebClient } from '@slack/web-api';

const client = new WebClient('mytoken');

(async () => {
  client.filesUploadV2({
    channel_id: 'C123',
    thread_ts: '173.029',
    content: 'test',
    filename: 'slack.json',
    title: 'test',
  });
})();
```
5. with `npm install ~/path/to/node-slack-sdk/packages/web-api`  the above should not create any typescript errors or warnings
6. change `channel_id` -> `channels`, you should see the following warning when running the app
```txt
[WARN]  web-api:WebClient:0 Although the 'channels' parameter is still supported for smoother migration from legacy files.upload, we recommend using the new channel_id parameter with a single str value instead (e.g. 'C12345').
```

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

### CODE REVIEW

File: packages/web-api/src/types/request/files.ts [hunk 1]
```diff
@@ -144,6 +144,8 @@ export type FileUploadV2 = FileUpload & {
   alt_text?: string;
   /** @description Channel ID where the file will be shared. If not specified the file will be private. */
   channel_id?: string;
+  /** @deprecated use channel_id instead */
```
Comment (WilliamBergamin) [inline packages/web-api/src/types/request/files.ts:147]: Not sure if we could do anything self then deprecate this 🤔

Comment (filmaj) [reply packages/web-api/src/types/request/files.ts:147]: Nailed it!

**Review by filmaj — APPROVED** [review]
Awesome! Nicely done. Hopefully sorting through all the different combinations of types/interfaces wasn't too bad 🙏 

And don't worry about the node 22 failures - I am looking into it. I think it's a new npm bug. As long as 18 and 20 pass, you are good! Merge away!
